/*
 * Copyright (C) 1994-2016 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *  
 * This file is part of the PBS Professional ("PBS Pro") software.
 * 
 * Open Source License Information:
 *  
 * PBS Pro is free software. You can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free 
 * Software Foundation, either version 3 of the License, or (at your option) any 
 * later version.
 *  
 * PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY 
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.
 *  
 * You should have received a copy of the GNU Affero General Public License along 
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 *  
 * Commercial License Information: 
 * 
 * The PBS Pro software is licensed under the terms of the GNU Affero General 
 * Public License agreement ("AGPL"), except where a separate commercial license 
 * agreement for PBS Pro version 14 or later has been executed in writing with Altair.
 *  
 * Altair’s dual-license business model allows companies, individuals, and 
 * organizations to create proprietary derivative works of PBS Pro and distribute 
 * them - whether embedded or bundled with other software - under a commercial 
 * license agreement.
 * 
 * Use of Altair’s trademarks, including but not limited to "PBS™", 
 * "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's 
 * trademark licensing policies.
 *
 */

/**
 * @file    checkkey.c
 *
 * @brief
 *		attr_recov.c - The 'checkkey.c' file goes with the source package is used to verify licesnse
 *
 * Included public functions are:
 *
 *	pbs_get_hostid	returning host id.
 *	init_license	initialize values of license structure
 */

#include <pbs_config.h>   /* the master config generated by configure */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <time.h>
#include <sys/types.h>
#include <netinet/in.h>
#include "portability.h"
#include "list_link.h"
#include "attribute.h"
#include "pbs_ifl.h"
#include "pbs_nodes.h"
#include "server.h"
#include "svrfunc.h"
#include "net_connect.h"
#include "pbs_error.h"
#include "log.h"
#include "pbs_license.h"
#include "work_task.h"
#include "job.h"


/********************   NOTE - NOTE - NOTE   ****************************
 * All keys have been stripped from this file. The following note	*
 * remains for historical reasons:					*
 * The 'checkkey.c' file goes with the source package is stripped down	*
 * to remove the secret key used for the old style and Trial licenses.	*
 * We must not let the key out. However, any changes made to this file	*
 * must be made to the version in packages/common as well.		*
 ************************************************************************/

char *pbs_licensing_license_location  = NULL;
long pbs_min_licenses		= PBS_MIN_LICENSING_LICENSES;
long pbs_max_licenses		= PBS_MAX_LICENSING_LICENSES;
int  pbs_licensing_linger	= PBS_LIC_LINGER_TIME;

/* Global Data Items: */
extern pbs_list_head svr_alljobs;
extern pbs_list_head svr_unlicensedjobs;

extern pbs_net_t pbs_server_addr;
unsigned long hostidnum;
int ext_license_server = 0;
int license_expired = 0;

void
check_expired_lic(struct work_task *ptask)
{
}

void
return_licenses(struct work_task *ptask)
{
}

int
pbs_get_licenses(int nlicense)
{
	return (0);
}

void
init_licensing(void)
{
}

int
status_licensing(void)
{
	return (0);
}

int
checkin_licensing(void)
{
	return (0);
}

void
close_licensing(void)
{
}
/**
 * @brief
 * 		returning host id.
 *
 * @return      Host ID
 */
unsigned long
pbs_get_hostid(void)
{
	unsigned long hid;

	hid = (unsigned long)gethostid();
	if (hid == 0)
		hid = (unsigned long)pbs_server_addr;
	return hid;
}
/**
 * @brief
 * 		initialize values of license structure
 *
 * @param[in]	licenses - pointer to the license block structure
 */
void
init_license(struct license_block *licenses)
{
	licenses->lb_trial = 0;
	licenses->lb_glob_floating = 1000000;
	licenses->lb_aval_floating = 1000000;
	licenses->lb_used_floating = 0;
	licenses->lb_high_used_floating = 0;
	licenses->lb_do_task = 0;
}

int
check_license(struct license_block *licenses)
{
	hostidnum = pbs_get_hostid();
	return (0);
}



/*
 ************************************************************************
 *
 * 		Licensing Jobs Functions
 *
 ************************************************************************
 */

/**
 * @brief
 * 		set_cpu_licenses_need - sets the job's ji_licneed to the number of CPUs needed for the
 *		assigned exec_vnode
 *
 * @param[in]	pjob	-	the job
 * @param[in]	exec_vnode	-	exec_vnode string used to compute job's required
 *								number of CPUs
 * @return	int
 * @retval	number of CPUs required for the given node set
 *
 * @par MT-Safe:	no
 *
 * @par Side Effects:
 *	None
 */
int
set_cpu_licenses_need(job *pjob, char *exec_vnode)
{
	char            *chunk;
	char            *last;
	int             hasprn;
	char            *vname;
	int             nelem;
	struct key_value_pair *pkvp;
	char            *execvnod = NULL;
	int             cpus_assn;
	int             cpus = 0;
	int		i;

	execvnod=strdup(exec_vnode);
	if (execvnod == NULL) {
		sprintf(log_buffer,
			"failed to strdup exec_vnode %s!", exec_vnode);
		log_err(errno, "set_cpu_licenses_need", log_buffer);
		return (1);	/* we don't know for sure - lie */
	}

	for (cpus_assn = 0, chunk = parse_plus_spec_r(execvnod, &last, &hasprn);
		chunk != NULL;
		chunk = parse_plus_spec_r(last, &last, &hasprn)) {
		if (parse_node_resc(chunk, &vname, &nelem, &pkvp) == 0) {
			attribute	*pattr;
			struct pbsnode	*pnode;

			/*
			 *	If vnode is already licensed, don't count
			 *	its CPUs as needed.
			 */
			if ((pnode = find_nodebyname(vname)) != NULL) {
				pattr = &pnode->nd_attr[(int) ND_ATR_License];
				if ((pattr->at_flags & ATR_VFLAG_SET) &&
					(pattr->at_val.at_char == ND_LIC_TYPE_locked))
					continue;
			}

			for (i=0; i<nelem; i++) {
				if (strcasecmp("ncpus",
					(pkvp+i)->kv_keyw) == 0) {
					cpus += atoi((pkvp+i)->kv_val);
				}
			}
		}
	}

	(void)free(execvnod);

	if (cpus > 0) {
		cpus_assn += cpus;
	}

	pjob->ji_licneed = cpus_assn;
	return (cpus > 0 ? 1 : 0);
}

#if 0
static void
report_license_highuse(void)
{
	int u;

	if (licenses.lb_used_floating > licenses.lb_high_used_floating)
		licenses.lb_high_used_floating = licenses.lb_used_floating;


	/* record max number of lic used over time 		   	 */
	/* This information is logged into the accounting license file.  */

	u = licenses.lb_used_floating;
	if (u > usedlicenses.lu_max_hr)
		usedlicenses.lu_max_hr = u;
	if (u > usedlicenses.lu_max_day)
		usedlicenses.lu_max_day = u;
	if (u > usedlicenses.lu_max_month)
		usedlicenses.lu_max_month = u;
	if (u > usedlicenses.lu_max_forever)
		usedlicenses.lu_max_forever = u;
}
#endif

/**
 * @brief
 * 		allocate_cpu_licenses: takes care of allocating "pjob->ji_licneed" number of
 * 		cpu licenses to the job 'pjob'.
 *
 * @param[out]	pjob	-	the job
 *
 * @return	pjob->ji_licalloc	: is set to the actual # of cpu licenses assigned.
 * @retval	 actual # of cpu licenses assigned.
 * @retval	0	: nothing got assigned.
 * @note
 * 		NOTE: Must call set_cpu_licenses_need() first before calling this function
 * 		in order for licenses to actually get assigned. The set_cpu_licenses_need()
 * 		takes care of assigning a value to pjob->ji_licneed.
 */
void
allocate_cpu_licenses(job *pjob)
{
#if 0
	int        cpulic_need;     /* # of cpu licenses to satisfy       */
	int        cpulic_add;      /* # of cpu licenses to add to local pool */
	int        cpulic_got;	    /* # of cpu licenses added to local pool */

	if (pjob == NULL) {
		log_err(PBSE_INTERNAL, "allocate_cpu_licenses",
			"pjob is NULL so no action taken");
		return;
	}

	/* Used to clear pjob->ji_licalloc of job here, but we have to      */
	/* preserve this value - # of licenses allocated to the job, which  */
	/* is non-zero for a job that is in the process of requeueing.      */
	/* ji_licalloc is cleared in 4 places: job_alloc(), coming from     */
	/* server restart and job was previously running, clearing the      */
	/* list of unlicensed jobs for relicensing, and                     */
	/* deallocate_cpu_licenses().                                       */

	/* don't allocate licenses if there are still jobs in              */
	/* svr_unlicensejobs list waiting to be licensed.                  */
	if (GET_NEXT(svr_unlicensedjobs) !=  (job *)NULL) {
		log_event(PBSEVENT_DEBUG2, PBS_EVENTCLASS_JOB, LOG_DEBUG,
			pjob->ji_qs.ji_jobid,
			"Unable to allocate cpu licenses, other jobs are waiting to be licensed");
		return;
	}

	if (pjob->ji_licneed < 0) {
		/*
		 * This indicates that set_cpu_licenses_need() has
		 * not been called to initialize job's ji_licneed.
		 */
		log_joberr(PBSE_INTERNAL, "allocate_cpu_licenses",
			"ji_licneed not set so no cpu licenses allocated. ",
			pjob->ji_qs.ji_jobid);
		return;
	}
	cpulic_need = pjob->ji_licneed - pjob->ji_licalloc;

	/* allocate what is being requested */
	if (cpulic_need <= licenses.lb_aval_floating) {
		licenses.lb_aval_floating -= cpulic_need;
		licenses.lb_used_floating += cpulic_need;

		pjob->ji_licalloc += cpulic_need;

		sprintf(log_buffer,
			"Allocated %d cpu licenses, float avail global %d, float avail local %d, used locally %d",
			pjob->ji_licalloc, licenses.lb_glob_floating,
			licenses.lb_aval_floating, licenses.lb_used_floating);
		DBPRT(("%s\n", log_buffer))
		log_event(PBSEVENT_DEBUG3, PBS_EVENTCLASS_JOB,
			LOG_DEBUG, pjob->ji_qs.ji_jobid, log_buffer);

		report_license_highuse();

	}

	update_FLic_attr();
#else
	if (pjob == NULL) {
		log_err(PBSE_INTERNAL, "allocate_cpu_licenses",
			"pjob is NULL so no action taken");
		return;
	}
	/* The following line works around the check in set_nodes() */
	pjob->ji_licalloc = 1;
#endif
}

/**
 * @brief
 * 		deallocate_cpu_licenses: any assigned cpu licenses of job 'pjob' is
 * 		returned to the local license pool.
 *
 * @param[in,out]	pjob	-	the job
 */
void
deallocate_cpu_licenses(job *pjob)
{
#if 0
	int	used_floating_orig;

	if (pjob == NULL) {
		log_err(PBSE_INTERNAL, "deallocate_cpu_licenses",
			"pjob is NULL so no action taken");
		return;
	}

	if (pjob->ji_licalloc <= 0)
		return;	/* nothing to deallocate */

	used_floating_orig = licenses.lb_used_floating;
	licenses.lb_used_floating -= pjob->ji_licalloc;

	if (licenses.lb_used_floating < 0) { /* paranoia: gone negative */
		licenses.lb_used_floating = 0;
		licenses.lb_aval_floating += used_floating_orig;
		sprintf(log_buffer,
			"licenses.lb_used_floating gone negative! Reset it back to 0 and license.lb_aval_floating is now %d",
			licenses.lb_aval_floating);
		log_event(PBSEVENT_DEBUG2, PBS_EVENTCLASS_JOB, LOG_DEBUG,
			pjob->ji_qs.ji_jobid, log_buffer);

	} else {
		licenses.lb_aval_floating += pjob->ji_licalloc;
	}
	update_FLic_attr();

	sprintf(log_buffer,
		"Released %d cpu licenses, float avail global %d, float avail local %d, used locally %d",
		pjob->ji_licalloc, licenses.lb_glob_floating,
		licenses.lb_aval_floating, licenses.lb_used_floating);
	DBPRT(("%s\n", log_buffer))
	log_event(PBSEVENT_DEBUG3, PBS_EVENTCLASS_JOB, LOG_DEBUG,
		pjob->ji_qs.ji_jobid, log_buffer);
	pjob->ji_licalloc = 0;
#endif
}

/**
 * @brief
 * 		clear_and_populate_svr_unlicensedjobs - removes all job entries from the
 *		svr_unlicensedjobs list, and re-populates the list
 *		with all currently running/exiting jobs (not suspended jobs).
 *
 */

void
clear_and_populate_svr_unlicensedjobs(void)
{
	job *pjob;

	while ((pjob = GET_NEXT(svr_unlicensedjobs)))
		delete_link(&pjob->ji_unlicjobs);

	/* repopulate the list */
	pjob = (job *)GET_NEXT(svr_alljobs);

	while (pjob  != (struct job *)0) {

		if (((pjob->ji_qs.ji_state == JOB_STATE_RUNNING) &&
			((pjob->ji_qs.ji_svrflags & JOB_SVFLG_Suspend) == 0)) &&
			!is_linked(&svr_unlicensedjobs, &pjob->ji_unlicjobs)) {
			append_link(&svr_unlicensedjobs, &pjob->ji_unlicjobs,
				pjob);
			pjob->ji_licalloc = 0;
		}
		pjob = GET_NEXT(pjob->ji_alljobs);
	}

}


/**
 * @brief
 * 		relicense_svr_unlicensedjobs - go through the svr_unlicensedjobs list
 *   	and attempt to obtain as much licenses available to relicense the jobs.
 * @note
 * 		NOTE: Before calling this function, you may invoke the
 *       clear_and_populate_svr_unlicensedjobs() function first,
 *       so that the list is populated with jobs that are currently running.
 *       The list is also updated by the calls to set_nodes() in node_manager.c.
 *
 * @par Algorithm:
 *      For each job in svr_unlicensedjobs list,
 *		calculate # of cpu licenses still needed by the job (job_needs)
 *              If job_need <= 0  then remove job from the svr_unlicensedjobs
 *                    list
 *              Otherwise,
 *                    See if there are usable licenses
 *                     (# avail in local pool + # avail in global license pool)
 *                   available. If so, then
 *                   Attempt to satisfy the job by assigning it:
 *                           MIN(job_needs, # of usable licenses)
 *                   checking out as much additional licenses from the global
 *                   license pool needed to satisfy the job.
 *                   If satisfied, set job->licalloc to the actual # of
 *                       assigned.
 *                   If job->licalloc  becomes equal to the # of cpus
 *                      requested by the job, then
 *                             the job is fully licensed so it is
 *                             removed from the svr_unlicensedjobs list.
 *       done
 */
void
relicense_svr_unlicensedjobs(void)
{
#if 0
	job *pjob, *next_pjob;
	int  job_needs;
	int  cpulic_total;
	int  cpulic_allocated;
	int  job_needs_min;	/* min # of cpu licenses that can satisfy job */

	next_pjob = NULL;
	for (pjob = (job *)GET_NEXT(svr_unlicensedjobs);
		pjob != NULL; pjob = next_pjob) {

		next_pjob = (job *)GET_NEXT(pjob->ji_unlicjobs);
		if (pjob->ji_licneed < 0) {
			/*
			 * This indicates that set_cpu_licenses_need() has
			 * not been called to initialize job's ji_licneed.
			 */
			sprintf(log_buffer, "ji_licneed not set so no cpu "
				"licenses allocated.");
			log_joberr(PBSE_INTERNAL, __func__, log_buffer,
				pjob->ji_qs.ji_jobid);
			continue;
		}

		job_needs = pjob->ji_licneed - pjob->ji_licalloc;

		if (job_needs <= 0) {
			/* delete since fully licensed or over-licensed */
			delete_link(&pjob->ji_unlicjobs);
			continue;
		}
		cpulic_total = licenses.lb_glob_floating + \
					licenses.lb_aval_floating;

		if (cpulic_total == 0) {
			break;	/* no licenses available */
		}

		/* try to satisfy MIN(# needed by job, # of usable licenses) */
		if (job_needs < cpulic_total) {
			job_needs_min = job_needs;
		} else {
			job_needs_min = cpulic_total;
		}

		sprintf(log_buffer,
			"Job is not fully licensed - needs %d cpu licenses, can get %d ",
			job_needs, job_needs_min);
		DBPRT(("%s\n", log_buffer))
		log_event(PBSEVENT_DEBUG3, PBS_EVENTCLASS_JOB,
			LOG_DEBUG, pjob->ji_qs.ji_jobid, log_buffer);

		/* now let's allocate cpu licenses */
		if (job_needs_min <= licenses.lb_aval_floating) {
			cpulic_allocated = job_needs_min;
		} else {
			cpulic_allocated = licenses.lb_aval_floating;
		}

		if (cpulic_allocated > 0) {
			pjob->ji_licalloc += cpulic_allocated;
			sprintf(log_buffer,
				"Added %d cpu licenses, total %d", cpulic_allocated,
				pjob->ji_licalloc);
			DBPRT(("%s\n", log_buffer))
			log_event(PBSEVENT_DEBUG2, PBS_EVENTCLASS_JOB,
				LOG_DEBUG, pjob->ji_qs.ji_jobid, log_buffer);
			licenses.lb_aval_floating -= cpulic_allocated;
			licenses.lb_used_floating += cpulic_allocated;

			report_license_highuse();

		}

		if (pjob->ji_licalloc == pjob->ji_licneed) { /* satisfied */
			log_event(PBSEVENT_DEBUG2, PBS_EVENTCLASS_JOB,
				LOG_DEBUG, pjob->ji_qs.ji_jobid,
				"fully licensed");
			delete_link(&pjob->ji_unlicjobs);
		}
	}

	update_FLic_attr();
#endif
}




